### ISSUE TITLE
As a player, I’d like to be able to choose my clothes AND my food

### ISSUE THREAD

**Issue by palrogg** [IMICovidou/Covidou#106]
It seems kitchen card gets shortcutted after clothes card

**Comment by Dobios** [comment]
This was a game design decision early on and not really a bug.

**Comment by palrogg** [comment]
Je viens d’en reparler avec @yrochat: on était en fait d’accord sur le fait d’avoir les deux choix (mais seulement dans l’ordre 1) habits 2) nourriture, pas de possibilité de revenir aux habits après la cuisine)

**Comment by yrochat** [comment]
@palrogg question : les sprites de Damien dans la cuisine le montrent tous en caleçon, non ? Il faudrait donc l'ordre 1) nourriture 2) habits, à moins de faire de nouveaux sprites.

**Comment by yrochat** [comment]
Ici je préférerais que pour passer à la suite il faille cliquer sur l'ordinateur plutôt que sur Damien. Est-ce possible ?
