### ISSUE TITLE
Student minigame: first occurrence should be short and easy, second one should be faster

### ISSUE THREAD

**Issue by palrogg** [IMICovidou/Covidou#113]
@astonedf on est d’accord, le minijeu de l’étudiant doit être simple (et court) la première fois avant d’augmenter en difficulté?

**Comment by astonedf** [comment]
Oui, j'aime bien le fait qu'ils soient plus espacé, mais c'est vrai que la première fois le jeu pourrais être plus court. A la base c'est sensé être en janvier/février donc pas sensé avoir le format cours zoom, mais il fait ses devoirs. Il faudrait un autre fond et sans les notifications. On peut en tout cas enlever les notifications comme ça ça rajoute un nouvel élément la deuxième fois qu'on joue.
