### ISSUE TITLE
As a player, I would like to see what percentage of people made the same decisions as me

### ISSUE THREAD

**Issue by palrogg** [IMICovidou/Covidou#118]
This implies following steps:
- [x] Insert player choices in an online database
- [x] End screen: for each measurable choice,
	- [x] query database for ratio of players who made the same decision
	- [x] display this decision as a % (with a bar chart?). Cf. Telltale: “You and ##% made Patrick pick all toilet paper”

**Comment by palrogg** [comment]
La moralité dans Telltale:
![Capture d’écran 2020-07-17 à 08 52 46](https://user-images.githubusercontent.com/12730304/87757424-eaa2fe00-c80a-11ea-9274-b792e41853c5.png)

@SadBermuda @astonedf on pourra discuter lundi de comment on arrive à intégrer ces comparaisons dans le style du jeu! Il faudra sans doute restreindre le nombre de comparaisons pour que ce soit digeste (à ce stade j’ai 4 comparaisons pour Damien, 3 pour la mère, 2 pour l’indépendant et 2 pour la grand-mère, total 11), ou rendre leur affichage aléatoire.

**Comment by yrochat** [comment]
J'aime l'idée avec les choix de mélanger les trucs anodins et les trucs avec une implication morale, mais s'il faut restreindre on peut le faire sur ces derniers.

**Comment by astonedf** [comment]
Je pense qu'on peut mettre les scores des mini-jeux tout de suite après et pas à la fin (vous avez mis 01:34 à ranger la chambre et vous avez acheté ces aliments/dépensé tant)
Donc si on a 2 pour Damien (sortir + habit ou nourriture - sauf si on donne la possibilité au joueur de choisir les 2), une pour la mère (sortir au parc), une pour l'indépendant (le conseil de couple) et 2 pour la grand-mère (conseil remède et coiffeur) ça me parait pas mal. Et y'a le badge de lecteur encore, je sais pas si on le mettrait au même endroit

**Comment by palrogg** [comment]
> Je pense qu'on peut mettre les scores des mini-jeux tout de suite après et pas à la fin (vous avez mis 01:34 à ranger la chambre et vous avez acheté ces aliments/dépensé tant)

Nouvelle issue #145 

> Donc si on a 2 pour Damien (sortir + habit ou nourriture - sauf si on donne la possibilité au joueur de choisir les 2), une pour la mère (sortir au parc), une pour l'indépendant (le conseil de couple) et 2 pour la grand-mère (conseil remède et coiffeur) ça me parait pas mal (6 au total). Et y'a le badge de lecteur encore, je sais pas si on le mettrait au même endroit

Après discussion en séance, on affiche donc un pourcentage par personnage:
- [ ] Damien: sortir ou non
- [ ] Mère: sortie au parc ou non
- [ ] Grand-mère: coiffeur ou non
- [ ] Indépendant: conseil couple

On essaiera de glisser les autres choix en texte si le temps nous le permet.
