### ISSUE TITLE
Need help: I've tried to manipulate the dialogs in Florence's scene

### ISSUE THREAD

**Issue by yrochat** [IMICovidou/Covidou#138]
I've tried two things and none worked. (Objective is to have less text displayed at once.)

I wanted to lighten her text and thought we could show a preview: when her kids ask to go out to the park, it would simply display "Yes" or "No". I used Patrick's dialogs as a model but couldn't make it work.

Then I thought I would reduce the length and move the "clean your rooms" at the end but my code (below) doesn't work. The kids' last answer isn't displayed. What am I doing wrong?

`{
	"florence": {
		"name": "Florence",
		"text": [
			"Ok, vous n'avez plus l'école, mais…",
            "Ça ne veut pas dire que vous êtes en vacances!",
            "La maîtresse m'a écrit.\nVous avez reçu des devoirs à faire."
		],
		"choices": [],
		"goto": ["kids"]
	},
	"kids": {
		"name": "Maxime et Liliane",
		"text": [
            "Mais Maman, ça fait trop longtemps qu'on n'est pas sortis!", 
            "On peut aller au jouer au parc avant, s'il te plaît? Alleeeeeeeez.",
            "On fera attention, promis!"
		],
		"choices": [
            {
                "text": "Bon, d'accord! Ce matin vous avez été sages.",
                "goto": "merci"
            },
            {
                "text": "Non, je vous ai déjà expliqué pourquoi.",
                "goto": "oh"
            }
        ],
		"goto": ["merci", "oh"]
    },
    "merci": {
		"name": "Maxime et Liliane",
		"text": [
			"Merci Maman!"
		],
		"choices": [],
		"goto": ["finOui"]
    },
    "finOui": {
		"name": "Florence",
		"text": [
			"Mais vous devez d'abord ranger votre chambre."
		],
		"choices": [],
		"goto": []
    },
    "oh": {
		"name": "Maxime et Liliane",
		"text": [
			"Mais rhooo! Maman, t'es pas gentille."
		],
		"choices": [],
		"goto": ["finNon"]
	},
    "finNon": {
		"name": "Florence",
		"text": [
			"Et vous allez me faire le plaisir de ranger votre chambre."
		],
		"choices": [],
		"goto": []
    }
}
`

**Comment by yrochat** [comment]
Sorry that the formatting of my code is not taken into account.

<img width="749" alt="Screenshot 2020-07-22 at 01 37 43" src="https://user-images.githubusercontent.com/3351331/88117652-f94b3580-cbbb-11ea-9428-049dfb70a444.png">

**Comment by palrogg** [comment]
Could you push your code to a branch, so we could give it a proper look? Thanks in advance :-)
Maybe a `goto` is missing…

**Comment by palrogg** [comment]
Actually the issue seems to be you put your `goto` in lists, it should be `"goto": "finOui"` and `"goto": "finNon"` instead

**Comment by yrochat** [comment]
If I delete the []'s after `"goto"` then it stops working.

I've commited a version that works but one line of text is not considered. Therefore I repeated it and the game includes the second one.

See lisne 34 and 51 of florenceDialogMarch.json

**Comment by palrogg** [comment]
Ok! Forget what I said before :-) I don’t understand why it doesn’t work when the "text" list contains only one item. Maybe @Dobios has an idea

**Comment by Dobios** [comment]
I'm not quite sure that I understand what your problem is here, what isn't working?

**Comment by yrochat** [comment]
@Dobios it's working but look at the code 😅

**Comment by palrogg** [comment]
Fixed https://github.com/IMICovidou/Covidou/commit/9d18e70df0f2dd29a92913e4f3bb4d0458ae188e
