### ISSUE TITLE
Need help: I'd like to add sounds but I need to understand how it works first

### ISSUE THREAD

**Issue by yrochat** [IMICovidou/Covidou#144]
In the Grandma Scene, I wanted to include the cat sound. I looked at the how the pageTurn works.

First pageTurn is loaded, so I loaded the cat sound too https://github.com/IMICovidou/Covidou/blob/sounds/src/scenes/cards/GrandmaScene/livingRoomCard.js#L128

Then it's added to the scene : https://github.com/IMICovidou/Covidou/blob/sounds/src/scenes/cards/GrandmaScene/livingRoomCard.js#L168

Eventually the sound is added after the sprite is added : https://github.com/IMICovidou/Covidou/blob/sounds/src/scenes/cards/GrandmaScene/livingRoomCard.js#L187

What am I doing wrong ?

**Comment by palrogg** [comment]
The issue is the cat sound is very low, isn’t it?

**Comment by yrochat** [comment]
@astonedf has implemented the cat scene and I will use it as an example https://github.com/IMICovidou/Covidou/commit/9a81c37f1be7658d6679b5f1f98e68cbf1bb5bea

Indeed the cat sound is too low.

**Comment by palrogg** [comment]
Petite marche à suivre:
1. charger le son dans `preload()`, exemple dans buildingScene.js:
```
this.load.audio("theme", "sounds/building/theme.mp3");
this.load.audio("click", "sounds/UI/UIClick.wav");
```

2. ajouter le son à la scène. La variable contient le suffixe Sound, pour éviter de confondre avec des sprites ou des actions:
`this.clickSound = this.sound.add("click");`

3. jouer le son au moment voulu, par exemple au moment d’un clic sur «Nouvelle partie»:
`this.clickSound.play();`
