### ISSUE TITLE
[BUG] Sprites get displaced when the screen ratio gets too low

### ISSUE THREAD

**Issue by Dobios** [IMICovidou/Covidou#49]
In the case of a very vertical screen (vertical resolution >> horizontal resolution) sprites tend to get displaced along the horizontal axis. This is due to the new resize system and can be fixed by adjusting the precomputed horizontal ratio factor.

**Comment by yrochat** [comment]
[LG G6 ratio 1:2]
In the new game screen :
- new game is not centered
- the upper left window overlaps with the balcony
- the lower left car overlaps with the car in the middle
