### ISSUE TITLE
The prototype scene should be split up into two or more scenes to avoid long loading times.

### ISSUE THREAD

**Issue by Dobios** [IMICovidou/Covidou#58]
An idea for the split would be to have the larger cards (like the zoom minigame) be a separate scene rather than a card in a scene.  
We would thus have a split as follow:  
- Wake up, Chose path, clothes & kitchen in the same scene.
- Computer, zoom minigame and message in an other scene.    

We could also imagine splitting the first one split it two different scenes if the initial loading time is still too long.

**Comment by yrochat** [comment]
One possibility : have no choice of order and impose "in front of cupboard & kitchen" -> "choice of habits" -> "in front oc cupboard & kitchen" -> "kitchen" -> "zoom".

Not sure it is super important to be able to choose between scenes, and it some cases people won't see the kitchen at all.
