### ISSUE TITLE
As a player, I would like to have a shaking animation that shows me what's intractable in the scene.

### ISSUE THREAD

**Issue by Dobios** [IMICovidou/Covidou#9]

**Comment by Dobios** [comment]
This should be done by having a JS wiggle animation + motion-blur shading (or Gaussian blur, but that might seem a bit off...)

**Comment by palrogg** [comment]
Si ça peut donner des idées, un test que j'avais fait avec PIXI (utilisé sous le capot par Phaser):
https://jsfiddle.net/palrogg/Lx1phwq9/latest/

Le “glow” [est dans un fichier généré à l’avance](https://res.cloudinary.com/dogfight/image/upload/v1532244828/outfit/blue_sun_80px_glow.png) et la variation se fait seulement sur l'alpha du glow (sinon, ça prend vite pas mal de ressources)

**Comment by Dobios** [comment]
We've opted for hand drawn glow instead.
